ERROR - 2022-06-26 21:08:10 --> Error connecting to the database: No connection could be made because the target machine actively refused it.

CRITICAL - 2022-06-26 21:08:10 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it.

#0 C:\Users\muhammad_aftabuddin\Documents\Internship\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\Users\muhammad_aftabuddin\Documents\Internship\system\Database\BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\Users\muhammad_aftabuddin\Documents\Internship\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#3 C:\Users\muhammad_aftabuddin\Documents\Internship\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#4 C:\Users\muhammad_aftabuddin\Documents\Internship\app\Controllers\userController.php(84): CodeIgniter\BaseModel->first()
#5 C:\Users\muhammad_aftabuddin\Documents\Internship\system\CodeIgniter.php(824): App\Controllers\userController->auth()
#6 C:\Users\muhammad_aftabuddin\Documents\Internship\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\userController))
#7 C:\Users\muhammad_aftabuddin\Documents\Internship\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\Users\muhammad_aftabuddin\Documents\Internship\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\Users\muhammad_aftabuddin\Documents\Internship\system\Commands\Server\rewrite.php(43): require_once('C:\\Users\\muhamm...')
#10 {main}
CRITICAL - 2022-06-26 21:08:10 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\Users\muhammad_aftabuddin\Documents\Internship\app\Views\errors\html\error_exception.php:96
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\Users\\muhamm...', 96, Array)
#1 C:\Users\muhammad_aftabuddin\Documents\Internship\app\Views\errors\html\error_exception.php(96): print_r(Object(App\Controllers\userController), true)
#2 C:\Users\muhammad_aftabuddin\Documents\Internship\system\Debug\Exceptions.php(229): include('C:\\Users\\muhamm...')
#3 C:\Users\muhammad_aftabuddin\Documents\Internship\system\Debug\Exceptions.php(232): CodeIgniter\Debug\Exceptions->CodeIgniter\Debug\{closure}()
#4 C:\Users\muhammad_aftabuddin\Documents\Internship\system\Debug\Exceptions.php(116): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#5 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptio
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
